# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

  build-asan:
    name: Build and test with AddressSanitizer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Install clang-14
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-14 clang++-14

    - name: Configure CMake with ASAN
      env:
        CC: /usr/bin/clang-14
        CXX: /usr/bin/clang++-14
      run: |
        cmake -B debug-build-asan \
          -DCMAKE_BUILD_TYPE=Debug \
          -DENABLE_WERROR=ON \
          -DENABLE_ASAN=ON \
          -DENABLE_UB_SANITIZER=ON \
          -DFIBER_STACK_SIZE=1280Kb \
          -DTEST_BUILD=ON

    - name: Build with ASAN
      run: cmake --build debug-build-asan --config Debug

    - name: Test with ASAN
      env:
        ASAN: ON
        ASAN_OPTIONS: debug=true:heap_profile=0:detect_invalid_pointer_pairs=3:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0
      run: |
        ./debug-build-asan/routes GehringHomberger1000/C1_10_1.TXT C1_10_1.sol --lower_bound 100 --log_level=normal
